name: build

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - "feature/*"
      - "main"

# This is conservative: ideally we'd include branch and stage in this key
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency: deploy-python-simulator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      # Note: This workflow will not run on forks without modification; we're open to making steps
      #       that rely on our deployment infrastructure conditional. Please open an issue.
      - uses: actions/checkout@v3
      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install --no-save @calliope-edu/website-deploy-aws-config # @microbit-foundation/website-deploy-aws@0.3.0 @microbit-foundation/website-deploy-aws-config@0.7.1 @microbit-foundation/circleci-npm-package-versioner@1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node ./bin/print-ci-env.js >> $GITHUB_ENV
      - run: node ./bin/print-ci-env.js
      - run: node ./bin/print-ci-env-public-url.js >> $GITHUB_ENV
      - run: node ./bin/print-ci-env-public-url.js
#      - run: npm run ci:update-version
      - run: ./ci-build.sh
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://${{ env.DEPLOY_PATH }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WEB_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_DEPLOY_AWS_SECRET_ACCESS_KEY }}
#      - run: npm run invalidate
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.WEB_DEPLOY_AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.WEB_DEPLOY_AWS_SECRET_ACCESS_KEY }}
